### ISSUE TITLE
access to dlang.org and other repos

### ISSUE THREAD

**Issue by wilzbach** [dlang-bots/mention-bot#8]
It seems that the dlang-bot doesn't have access to the dlang.org repo (?) and thus it fails at assigning a PR, e.g.

https://github.com/dlang/dlang.org/pull/1441

CC @CyberShadow @MartinNowak

**Comment by CyberShadow** [comment]
Added @dlang-bot to [Team dlang.org](https://github.com/orgs/dlang/teams/team-dlang-org).

**Comment by wilzbach** [comment]
Thanks :)
